/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhc_aeojcodesandbox_sandbox_NativeSandBox */

#ifndef _Included_com_zhc_aeojcodesandbox_sandbox_NativeSandBox
#define _Included_com_zhc_aeojcodesandbox_sandbox_NativeSandBox
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhc_aeojcodesandbox_sandbox_NativeSandBox
 * Method:    run
 * Signature: (Lcom/zhc/aeojcodesandbox/sandbox/Config;)Lcom/zhc/aeojcodesandbox/sandbox/Result;
 */
JNIEXPORT jobject JNICALL Java_com_zhc_aeojcodesandbox_sandbox_NativeSandBox_run
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
